modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="prean"
version="1.2.1"
displayName="prean"
credits="This Mod Is Make By PROMAN or Hriday Khanna."
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="PROMAN"

[[dependencies.prean]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




